version: "3.8"

volumes:
  keycloak_db_data:


services:

  citural-keycloak-db:
    image: postgres:14.4-alpine
    container_name: citural-keycloak-db
    # volumes:
    #   - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  citural-keycloak-service:
    container_name: citural-keycloak-service
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - citural-keycloak-db
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      # - KEYCLOAK_LOGLEVEL=TRACE
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://citural-keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    command: [ "start-dev" ]       
    # command: [ "start", "--optimized" ]
    ports:
      - "8800:8080"
      - "8443:8443"
